# Generated by Django 4.1.7 on 2023-06-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customer_address1_customer_address2_customer_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
    ]
